tap homebrew/versions
tap caskroom/fonts
tap homebrew/services
tap homebrew/apache
tap homebrew/completions

update

# setup gnu utils in place of os x provided enes
install gcc
install vim --override-system-vi
install vimpager
install htop-osx
install watch
install wget

# dev tools
install awscli
install bash
install bash-completion
install ctags
install curl --with-ssh
link --force curl
install fish
install git
install gradle
install maven
install tmux

# postgres related
install postgresql
install pgbadger
install pg_top
install postgis
install pgformatter

# langs
install go
install groovy
install lua
install python
# install ruby via rbenv
install rbenv
install ruby-build
install rbenv-bundler

# other assorted things
install brew-pip
install fontconfig
install freetype
install fswatch
install gist
install gnupg
install gpgme
install httpie
install jpeg
install jsonpp
install netcat
install nmap
install node
install openconnect
install parallel
# install from source to avoid accidentaly upgrading pg, if pg version number has been pinned
install --build-from-source pgcli
install readline
install ssh-copy-id
install stow
# reattach-to-user-namespace allows pbcopy/pbpaste and most importantly, launctl, to play nice with tmux
install reattach-to-user-namespace

pin postgresql

cleanup
