tap homebrew/services

update

# setup gnu utils in place of os x provided enes
install coreutils
install gcc
install vim
install vimpager --HEAD
install htop-osx
install watch
install wget

# dev tools
install awscli
install bash
install bash-completion
install --HEAD universal-ctags/universal-ctags/universal-ctags
install curl
link --force curl
install fish
install fzf
install gimme
install git
install gox
install hub
install kubectx
install kubernetes-cli
install shellcheck
install tmux

# langs
install go
install python
install rbenv
install ruby-build
install rbenv-bundler
install tfenv
install terraform_landscape

# other assorted things
install brew-pip
install fontconfig
install freetype
install fswatch
install jq
install moreutils
install netcat
install nmap
install readline
install the_silver_searcher
install ssh-copy-id
install stow
# reattach-to-user-namespace allows pbcopy/pbpaste and most importantly, launctl, to play nice with tmux
install reattach-to-user-namespace
install vault

cleanup
