tap homebrew/services

update

# setup gnu utils in place of os x provided enes
install gcc
install vim
install vimpager --HEAD
install htop-osx
install watch
install wget

# dev tools
install awscli
install bash
install bash-completion
install ctags
install curl
link --force curl
install fish
install fzf
install gimme
install git
install gradle
install hub
install maven
install kubectx
install kubernetes-cli
install shellcheck
install tmux

# postgres related
install postgresql
install pgbadger
install pg_top
install postgis
install pgformatter

# langs
install go
install groovy
install lua
install node
install python
# install ruby via rbenv
install rbenv
install ruby-build
install rbenv-bundler
install tfenv
install terraform_landscape

# other assorted things
install brew-pip
install fontconfig
install freetype
install fswatch
install jq
install moreutils
install netcat
install nmap
install openconnect
# install from source to avoid accidentaly upgrading pg, if pg version number has been pinned
install --build-from-source pgcli
install readline
install the_silver_searcher
install ssh-copy-id
install stow
# reattach-to-user-namespace allows pbcopy/pbpaste and most importantly, launctl, to play nice with tmux
install reattach-to-user-namespace

pin postgresql

cleanup
