#!/bin/bash
# crude replcaement script for running Brewfiles written when brew bundle was
# still supported (and even recommended over writing your own shell script!)
# by the homebrew devs
set -e
set -o pipefail

pushd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null

(brew --version && echo "brew already install") || (echo "installing homebrew" && ruby -e brew-starter.rb)

echo "checking brew install for issues"
brew doctor || true

echo "updating brew indexes"
brew update

echo "installing brews"
cat Brewfile | grep -v "^#" | grep -v '^$' | \
while read CMD; do
  echo "doing $CMD"    
  brew $CMD
done

echo "installing casks"
cat Caskfile | grep -v "^#" | grep -v '^$' | \
while read CMD; do
  echo "$CMD"
  brew $CMD
done

# probably not going to do anything, but
brew upgrade

echo "cleaning up old versions"
brew cleanup

# TODO properly trap on exit and popd back to where we came from
popd > /dev/null
