#!/bin/bash
#setup homebrew, dotfiles on a new machine
#not currently tested beyond the stow portion of things, 
#need to set up an empty vagrant image for testing first
set -e
set -o pipefail

pushd $(dirname $0) > /dev/null


#### OS X or Linux? ####
UNAME=$(uname -s)
OS="unknown"
echo "proceeding with hassling stowaways for $UNAME"

if [ "Linux" = "$UNAME" ]; then
    #### install git and stow for linux ####
    sudo apt-get install stow git -y;
    OS="linux"
elif [ "Darwin" = "$UNAME" ]; then
    #### install dev tools, Homebrew and git ####
    xcode-select --install
    read -p "press return when xcode cli tools install is complete to continue"
    curl -fsSL "https://raw.github.com/Homebrew/homebrew/go/install" > "/tmp/install_brew.rb"
    ruby "/tmp/install_brew.rb"
    rm "/tmp/install_brew.rb"
    OS="osx"
else
    "Don't know what to do with stowaways with a uname of $UNAME"
    exit 1;
fi


#### generate new ssh keys ####
ssh-keygen

read -p "about to clone dotfiles repo, go ahead and add your new ssh key to github first, press enter when done"

#### get dotfiles repo ####
GITDIR="$HOME/git"
mkdir -p "$GITDIR"
pushd "$GITDIR" > /dev/null
DOTREPO="dotfiles"
git clone "git@github.com:ianferguson/$DOTREPO.git"
pushd "$DOTREPO" > /dev/null

#### install brew bundles ####
if [ "osx" = "$OS" ]; then
    pushd brew > /dev/null
    brew bundle Brewfile
    brew bundle Caskfile
    brew doctor || true
    popd > /dev/null
fi;

#### Stow Stuff ####
#first stow a stow ignore, so we avoid any DS_Store stuff forever
echo "stowing stow files"
stow --ignore ".DS_Store" -t ~ stow

STOWAWAYS=(fish git psql tmux htop bash_$OS mongo ssh vim)
for STOWAWAY in ${STOWAWAYS[@]}; do
    echo "stowing $STOWAWAY"
    stow -R --adopt -t ~ $STOWAWAY
done;

#tomcat settings
stow -R --adopt -t $CATALINA_HOME tomcat
"$JAVA_HOME/bin/keytool"  -genkey -alias tomcat -keyalg RSA

popd > /dev/null
popd > /dev/null
popd > /dev/null
