#!/bin/bash
# assuming stow is already installed re run stow over a know/fixed list of stow packages
# note: if the target dirs for any of the packages already contain files in them you will get an
# an error since it's not possible to unstow and stow to them (-R), but this script assumes
# that everything was already run through the initial set up script and as such, already adopted
# and stowed. (this most specifically applies to tomcat)
set -u
set -e
set -o pipefail

# check for stow, will have > 0 exist status if it isn't here, and set -e will cause exit
stow -V

echo "stowing stow files"
stow --ignore ".DS_Store" -t ~ stow

STOWAWAYS=(fish git psql tmux htop mongo ssh vim)
for STOWAWAY in ${STOWAWAYS[@]}; do
    echo "stowing $STOWAWAY"
    stow -R --adopt -t ~ $STOWAWAY
done;

echo "stowing tomcat to $CATALINA_HOME"
stow -R --adopt -t "$CATALINA_HOME" tomcat

# No longer full OS agnostic, but I also don't actually use these scripts
# much on Linux, and when that time comes I'll just fix this along with the other 
# 100 things I'm going to need to tweak
KEY_TARGET="$HOME/Library/KeyBindings"
echo "stowing key bindings to $KEY_TARGET to make home/end work as expected"
mkdir -p "$KEY_TARGET"
stow -R --adopt -t "$KEY_TARGET" osx_keys
