#!/bin/bash
# assuming stow is already installed re run stow over a know/fixed list of stow packages
set -u
set -e
set -o pipefail

# check for stow, will have > 0 exist status if it isn't here, and set -e will cause exit
stow -V

echo "stowing stow files"
stow --ignore ".DS_Store" -t ~ stow

STOWAWAYS=(fish git psql tmux htop mongo ssh vim bash_$OS) 
for STOWAWAY in ${STOWAWAYS[@]}; do
    echo "stowing $STOWAWAY"
    stow -R --adopt -t ~ $STOWAWAY
done;

