#!/usr/local/bin/fish
# should be run once to set initial universal env vars on a new install, after tool installation is complete
set -Ux fish_greeting "Good morning sunshine!"

# Default editor, etc
set -Ux PAGER vimpager
set -Ux VISUAL vim
set -Ux EDITOR vim

# Go Pathes
set -Ux GOROOT (go env GOROOT)
set -Ux GOPATH ~/go

# Home Brew configuration
set -Ux HOMEBREW_NO_INSECURE_REDIRECT 1
set -Ux HOMEBREW_CASK_OPTS "--require-sha"

#### Java Pathing
set -Ux JAVA_TOOL_OPTIONS '-Djava.awt.headless=true'
set -Ux JAVA_HOME (/usr/libexec/java_home)

# AWS and Friends
set -Ux AWS_VAULT_KEYCHAIN_NAME login
set -Ux AWS_SESSION_TTL 24h
set -Ux AWS_ASSUME_ROLE_TTL 1h

set -Ux RBENV_SHELL fish

# prepend paths we want on the user's path
set -p fish_user_paths ~/.rbenv/shims
set -p fish_user_paths /usr/local/sbin
set -p fish_user_paths ~/bin
set -p fish_user_paths ~/.fzf/bin

# use awk to dedupe but preserve ordering
set -U fish_user_paths (echo $fish_user_paths | tr ' ' '\n' | awk '!uniq[$0]++')

