# atos
# Autogenerated from man page /usr/share/man/man1/atos.1.gz
# using Darwin man parser
complete -c atos -s o --description 'The path to a binary image file in which to look up symbols.'
complete -c atos -s p --description 'The process ID or the partial name of a current… [See Man Page]'
complete -c atos -o arch --description 'The particular architecure of a binary image fi… [See Man Page]'
complete -c atos -s l --description 'The load address of the binary image.'
complete -c atos -s s --description 'The slide value of the binary image -- this is … [See Man Page]'
complete -c atos -o printHeader --description 'If a process was specified, the first line of a… [See Man Page]'

