# atq
# Autogenerated from man page /usr/share/man/man1/atq.1.gz
# using Darwin man parser
complete -c atq -s b --description 'Is an alias for atq batch.'
complete -c atq -s c --description 'Cat the jobs listed on the command line to standard output.'
complete -c atq -s d --description 'Is an alias for atq atrm (this option is deprec… [See Man Page]'
complete -c atq -s f --description 'Read the job from file rather than standard input.'
complete -c atq -s l --description 'With no arguments, list all jobs for the invoking user.'
complete -c atq -s m --description 'Send mail to the user when the job has complete… [See Man Page]'
complete -c atq -s q --description 'Use the specified queue.'
complete -c atq -s r --description 'Remove the specified jobs.'
complete -c atq -s t --description 'Specify the job time using the \\*[Px] time format.'
complete -c atq -s v --description 'For atq atq, shows completed but not yet delete… [See Man Page]'

