# atrm
# Autogenerated from man page /usr/share/man/man1/atrm.1.gz
# using Darwin man parser
complete -c atrm -s b --description 'Is an alias for atrm batch.'
complete -c atrm -s c --description 'Cat the jobs listed on the command line to standard output.'
complete -c atrm -s d --description 'Is an alias for atrm atrm (this option is depre… [See Man Page]'
complete -c atrm -s f --description 'Read the job from file rather than standard input.'
complete -c atrm -s l --description 'With no arguments, list all jobs for the invoking user.'
complete -c atrm -s m --description 'Send mail to the user when the job has complete… [See Man Page]'
complete -c atrm -s q --description 'Use the specified queue.'
complete -c atrm -s r --description 'Remove the specified jobs.'
complete -c atrm -s t --description 'Specify the job time using the \\*[Px] time format.'
complete -c atrm -s v --description 'For atrm atq, shows completed but not yet delet… [See Man Page]'

