# autopoint
# Autogenerated from man page /opt/local/share/man/man1/autopoint.1.gz
# using Deroffing man parser
complete -c autopoint -l help --description 'print this help and exit.'
complete -c autopoint -l version --description 'print version information and exit.'
complete -c autopoint -s f -l force --description 'force overwriting of files that already exist.'
complete -c autopoint -s n -l dry-run --description 'print modifications but don\'t perform them AUTH… [See Man Page]'

