# batch
# Autogenerated from man page /usr/share/man/man1/batch.1.gz
# using Darwin man parser
complete -c batch -s b --description 'Is an alias for batch batch.'
complete -c batch -s c --description 'Cat the jobs listed on the command line to standard output.'
complete -c batch -s d --description 'Is an alias for batch atrm (this option is depr… [See Man Page]'
complete -c batch -s f --description 'Read the job from file rather than standard input.'
complete -c batch -s l --description 'With no arguments, list all jobs for the invoking user.'
complete -c batch -s m --description 'Send mail to the user when the job has complete… [See Man Page]'
complete -c batch -s q --description 'Use the specified queue.'
complete -c batch -s r --description 'Remove the specified jobs.'
complete -c batch -s t --description 'Specify the job time using the \\*[Px] time format.'
complete -c batch -s v --description 'For batch atq, shows completed but not yet dele… [See Man Page]'

