# chfn
# Autogenerated from man page /usr/share/man/man1/chfn.1.gz
# using Darwin man parser
complete -c chfn -s l --description 'If not specified, chfn will perform a search fo… [See Man Page]'
complete -c chfn -s u --description 'The user name to use when authenticating to the… [See Man Page]'
complete -c chfn -s s --description 'Attempt to change the user\'s shell to newshell.'

