# chsh
# Autogenerated from man page /usr/share/man/man1/chsh.1.gz
# using Darwin man parser
complete -c chsh -s l --description 'If not specified, chsh will perform a search fo… [See Man Page]'
complete -c chsh -s u --description 'The user name to use when authenticating to the… [See Man Page]'
complete -c chsh -s s --description 'Attempt to change the user\'s shell to newshell.'

