# compileHelp
# Autogenerated from man page /usr/share/man/man1/compileHelp.1
# using Darwin man parser
complete -c compileHelp -s f --description 'Force the output file to be created, even with no input files.'
complete -c compileHelp -s m --description 'Merge the contents of \\fIHELPFILE\\fR.'
complete -c compileHelp -s o --description 'Write output to \\fIFILE\\fR.'
complete -c compileHelp -o help --description 'Print usage message.  El.'

