# cups-config
# Autogenerated from man page /usr/share/man/man1/cups-config.1.gz
# using Deroffing man parser
complete -c cups-config -l api-version --description 'br Displays the current API version (major. minor).'
complete -c cups-config -l build --description 'br Displays a system-specific build number.'
complete -c cups-config -l cflags --description 'br Displays the necessary compiler options.'
complete -c cups-config -l datadir --description 'br Displays the default CUPS data directory.'
complete -c cups-config -l help --description 'br Displays the program usage message.'
complete -c cups-config -l image --description 'br When used with --libs, adds the CUPS imaging… [See Man Page]'
complete -c cups-config -l ldflags --description 'br Displays the necessary linker options.'
complete -c cups-config -l libs --description 'br Displays the necessary librarys to link to.'
complete -c cups-config -l serverbin --description 'br Displays the default CUPS binary directory, … [See Man Page]'
complete -c cups-config -l serverroot --description 'br Displays the default CUPS configuration file directory.'
complete -c cups-config -l static --description 'br When used with --libs, shows the static libr… [See Man Page]'
complete -c cups-config -l version --description '.'

