# edit
# Autogenerated from man page /usr/local/share/man/man1/edit.1
# using Type1
complete -c edit -s b -l background --description 'Launch TextWrangler in the background if it\'s n… [See Man Page]'
complete -c edit -l clean --description 'Piped data will be placed in an untitled docume… [See Man Page]'
complete -c edit -s c -l create --description 'Create the specified files, unless they exist a… [See Man Page]'
complete -c edit -s e -l encoding --description 'Specify the internet name of an encoding to ope… [See Man Page]'
complete -c edit -l front-window --description 'Opens the specified files as separate documents… [See Man Page]'
complete -c edit -s h -l help --description 'Display a basic help line with a summary of the… [See Man Page]'
complete -c edit -s l -l launch --description 'Launch TextWrangler (or activate it, if it\'s al… [See Man Page]'
complete -c edit -l new-window --description 'Opens the specified files as separate documents… [See Man Page]'
complete -c edit -s p -l print --description 'Print the specified files on your currently selected printer.'
complete -c edit -s t -l pipe-title --description 'Uses the specified string as the title of the w… [See Man Page]'
complete -c edit -s u -l create-unix --description 'Create the specified files, unless they exist a… [See Man Page]'
complete -c edit -l separate-windows --description 'Opens each of the specified files into its own text window.'
complete -c edit -s v -l version --description 'Display the current version number of the edit … [See Man Page]'
complete -c edit -s V -l short-version --description 'Display the short-form version number of the ed… [See Man Page]'
complete -c edit -l view-top --description 'Piped data will be placed into a new document w… [See Man Page]'
complete -c edit -l resume --description 'Used in combination with -w or --wait, this swi… [See Man Page]'

