# file
# Autogenerated from man page /usr/share/man/man1/file.1
# using Darwin man parser
complete -c file -s d --description 'Apply the default system tests; this is the def… [See Man Page]'
complete -c file -s D --description 'Print debugging messages.'
complete -c file -s I --description 'Causes the file command to output mime type str… [See Man Page]'
complete -c file -s M --description 'Like m, except that the default rules are not a… [See Man Page]'

