# filtercalltree
# Autogenerated from man page /usr/share/man/man1/filtercalltree.1.gz
# using Darwin man parser
complete -c filtercalltree -o invertCallTree --description 'Print the call tree from hottest to coldest stack frame.'
complete -c filtercalltree -o pruneCount --description 'Remove branches of the call tree that have coun… [See Man Page]'
complete -c filtercalltree -o pruneMallocSize --description 'Remove branches of the call tree that have mall… [See Man Page]'
complete -c filtercalltree -o chargeSystemLibraries --description 'Remove stack frames from all libraries in /Syst… [See Man Page]'
complete -c filtercalltree -o chargeLibrary --description 'Remove stack frames from library-name, while st… [See Man Page]'
complete -c filtercalltree -o keepBoundaries --description 'When charging libraries to callers, keep the to… [See Man Page]'

