# FixupResourceForks
# Autogenerated from man page /usr/share/man/man1/FixupResourceForks.1
# using Darwin man parser
complete -c FixupResourceForks -o 'q[uiet]' --description 'Suppress verbose diagnostics to standard output.'
complete -c FixupResourceForks -o nosetinfo --description 'Do not set file system metadata (type, creator,… [See Man Page]'
complete -c FixupResourceForks -o nodelete --description 'Leave the AppleDouble files in the directory af… [See Man Page]'

