# ftp
# Autogenerated from man page /usr/share/man/man1/ftp.1.gz
# using Darwin man parser
complete -c ftp -s 4 --description 'Forces ftp to only use IPv4 addresses.'
complete -c ftp -s 6 --description 'Forces ftp to only use IPv6 addresses.'
complete -c ftp -s A --description 'Force active mode ftp.'
complete -c ftp -s a --description 'Causes ftp to bypass normal login procedure, an… [See Man Page]'
complete -c ftp -s e --description 'Disables command line editing.'
complete -c ftp -s N --description 'Use netrc instead of ~/. netrc.  Refer to THE .'
complete -c ftp -s o --description 'When auto-fetching files, save the contents in output.'
complete -c ftp -s p --description 'Enable passive mode operation for use behind co… [See Man Page]'
complete -c ftp -s P --description 'Sets the port number to port.'
complete -c ftp -s q --description 'Quit if the connection has stalled for quittime seconds.'
complete -c ftp -s r --description 'Retry the connection attempt if it failed, paus… [See Man Page]'
complete -c ftp -s R --description 'Restart all non-proxied auto-fetches.'
complete -c ftp -s s --description 'Uses srcaddr as the local IP address for all connections.'
complete -c ftp -s V --description 'Disable verbose and progress, overriding the de… [See Man Page]'

