# git-rev-list
# Autogenerated from man page /usr/share/man/man1/git-rev-list.1
# using Deroffing man parser
complete -c git-rev-list -l no-walk --description 'Only show the given revs, but do not traverse their ancestors.'

