# git-log
# Autogenerated from man page /usr/share/man/man1/git-log.1
# using Deroffing man parser
complete -c git-log -o '<n>' --description 'Limits the number of commits to show.'
complete -c git-log -l no-walk --description 'Only show the given revs, but do not traverse their ancestors.'

