# heap
# Autogenerated from man page /usr/share/man/man1/heap.1.gz
# using Darwin man parser
complete -c heap -o guessNonObjects --description 'Look through the memory contents of each Object… [See Man Page]'
complete -c heap -o sumObjectFields --description 'Do the same analysis as with the guessNonObject… [See Man Page]'
complete -c heap -o showSizes --description 'Show the distribution of each malloc size for e… [See Man Page]'
complete -c heap -o addresses --description 'Print the addresses of all malloc blocks found … [See Man Page]'

