# ident
# Autogenerated from man page /usr/share/man/man1/ident.1
# using Deroffing man parser
complete -c ident -s q --description 'suppresses the warning given if there are no pa… [See Man Page]'
complete -c ident -s V --description 'prints ident \'s version number.'
complete -c ident -s z --description 'option, times are given with a numeric time zon… [See Man Page]'
complete -c ident -s s --description 'option of rcs (1) or ci (1).'

