# idn
# Autogenerated from man page /opt/local/share/man/man1/idn.1.gz
# using Deroffing man parser
complete -c idn -s h -l help --description 'Print help and exit.'
complete -c idn -s V -l version --description 'Print version and exit.'
complete -c idn -s s -l stringprep --description 'Prepare string according to nameprep profile.'
complete -c idn -s d -l punycode-decode --description 'Decode Punycode.'
complete -c idn -s e -l punycode-encode --description 'Encode Punycode.'
complete -c idn -s a -l idna-to-ascii --description 'Convert to ACE according to IDNA (default mode).'
complete -c idn -s u -l idna-to-unicode --description 'Convert from ACE according to IDNA.'
complete -c idn -l allow-unassigned --description 'Toggle IDNA AllowUnassigned flag (default off).'
complete -c idn -l usestd3asciirules --description 'Toggle IDNA UseSTD3ASCIIRules flag (default off).'
complete -c idn -l no-tld --description 'Don\'t check string for TLD specific rules Only … [See Man Page]'
complete -c idn -s n -l nfkc --description 'Normalize string according to Unicode v3. 2 NFKC.'
complete -c idn -s p -l profile --description 'Use specified stringprep profile instead Valid … [See Man Page]'
complete -c idn -l debug --description 'Print debugging information.'
complete -c idn -l quiet --description 'Silent operation AUTHOR Written by Simon Josefsson.'

