# isc-config
# Autogenerated from man page /usr/share/man/man1/isc-config.sh.1.gz
# using Deroffing man parser
complete -c isc-config -l cflags --description 'Prints the compiler command line options requir… [See Man Page]'
complete -c isc-config -l exec-prefix --description 'Prints the directory prefix used in the ISC BIN… [See Man Page]'
complete -c isc-config -l libs --description 'Prints the linker command line options used to … [See Man Page]'
complete -c isc-config -l prefix --description 'Prints the directory prefix used in the ISC BIN… [See Man Page]'
complete -c isc-config -l version --description 'Prints the version of the installed ISC BIND suite.'

