# krb5-send-pr
# Autogenerated from man page /opt/local/share/man/man1/krb5-send-pr.1.gz
# using Deroffing man parser
complete -c krb5-send-pr -s f --description 'specify a file (problem-report) which already c… [See Man Page]'
complete -c krb5-send-pr -s s --description 'Give the problem report the severity R severity .'
complete -c krb5-send-pr -s t --description 'Change mail address at the support site for problem reports.'
complete -c krb5-send-pr -s c --description 'Put  address in the   Cc: header of the message.'
complete -c krb5-send-pr -s P --description 'print the form specified by the environment var… [See Man Page]'
complete -c krb5-send-pr -s L --description 'print the list of available categories.   No mail is sent.'
complete -c krb5-send-pr -l request-id --description 'sends mail to the default support site, or  sit… [See Man Page]'
complete -c krb5-send-pr -s V --description 'Display the  krb5-send-pr version number.'

