# ksu
# Autogenerated from man page /opt/local/share/man/man1/ksu.1.gz
# using Deroffing man parser
complete -c ksu -s n --description 'Specify a Kerberos target principal name.'
complete -c ksu -s c --description 'Specify source cache name (e. g.   -c FILE:/tmp/my_cache).'
complete -c ksu -s k --description 'Do not delete the target cache upon termination… [See Man Page]'
complete -c ksu -s D --description 'turn on debug mode.'
complete -c ksu -s l -s r -o pf --description 'The ticket granting ticket options only apply t… [See Man Page]'
complete -c ksu -s p --description 'option specifies that the PROXIABLE option shou… [See Man Page]'
complete -c ksu -s f --description 'option specifies that the FORWARDABLE  option  … [See Man Page]'
complete -c ksu -s z --description 'restrict the copy of tickets from the source ca… [See Man Page]'
complete -c ksu -s Z --description 'Don\'t copy any tickets from the source cache to… [See Man Page]'
complete -c ksu -s q --description 'suppress the printing of status messages.'
complete -c ksu -s e --description 'ksu proceeds exactly the same as if it was invo… [See Man Page]'
complete -c ksu -o 'lag).' --description '.'
complete -c ksu -s a --description 'specify arguments to be passed to the target shell.'
complete -c ksu -o 'a.' --description 'The.'
complete -c ksu -o DPRINC_LOOK_AHEAD -o DCMD_PATH --description '.'

