# kvno
# Autogenerated from man page /opt/local/share/man/man1/kvno.1.gz
# using Deroffing man parser
complete -c kvno -s c --description 'specifies the name of a credentials cache to us… [See Man Page]'
complete -c kvno -s e --description 'specifies the enctype which will be requested f… [See Man Page]'
complete -c kvno -s q --description 'suppress printing.'
complete -c kvno -s h --description 'prints a usage statement and exits.'
complete -c kvno -s S --description 'specifies that krb5_sname_to_principal() will b… [See Man Page]'

