# launchctl
# Autogenerated from man page /usr/share/man/man1/launchctl.1.gz
# using Darwin man parser
complete -c launchctl -s w --description 'Overrides the Disabled key and sets it to false.'
complete -c launchctl -s F --description 'Force the loading of the plist.  Ignore the Disabled key.'
complete -c launchctl -s S --description 'Some jobs only make sense in certain contexts.'
complete -c launchctl -s D --description 'Look for plist 5 files ending in *. plist in the domain given.'
complete -c launchctl -s l --description 'What unique label to assign this job to launchd.'
complete -c launchctl -s p --description 'What program to really execute, regardless of w… [See Man Page]'
complete -c launchctl -s o --description 'Where to send the stdout of the program.'
complete -c launchctl -s e --description 'Where to send the stderr of the program.'

