# link
# Autogenerated from man page /usr/share/man/man1/link.1.gz
# using Darwin man parser
complete -c link -s F --description 'If the target file already exists and is a dire… [See Man Page]'
complete -c link -s h --description 'If the target_file or target_dir is a symbolic … [See Man Page]'
complete -c link -s f --description 'If the target file already exists, then unlink … [See Man Page]'
complete -c link -s i --description 'Cause link ln to write a prompt to standard err… [See Man Page]'
complete -c link -s n --description 'Same as h, for compatibility with other link ln… [See Man Page]'
complete -c link -s s --description 'Create a symbolic link.  ==========.'
complete -c link -s v --description 'Cause link ln to be verbose, showing files as t… [See Man Page]'

