# lndir
# Autogenerated from man page /usr/X11/man/man1/lndir.1.gz
# using Deroffing man parser
complete -c lndir -o silent --description 'Normally lndir outputs the name of each subdire… [See Man Page]'
complete -c lndir -o ignorelinks --description 'Causes the program to not treat symbolic links … [See Man Page]'
complete -c lndir -o withrevinfo --description 'Causes any source control manager subdirectorie… [See Man Page]'

