# locate
# Autogenerated from man page /usr/share/man/man1/locate.1.gz
# using Darwin man parser
complete -c locate -s 0 --description 'Print pathnames separated by an ASCII NUL chara… [See Man Page]'
complete -c locate -s S --description 'Print some statistics about the database and exit.'
complete -c locate -s c --description 'Suppress normal output; instead print a count o… [See Man Page]'
complete -c locate -s d --description 'Search in database instead of the default file name database.'
complete -c locate -s i --description 'Ignore case distinctions in both the pattern and the database.'
complete -c locate -s l --description 'Limit output to number of file names and exit.'
complete -c locate -s m --description 'Use mmap 2 instead of the stdio 3 library.'
complete -c locate -s s --description 'Use the stdio 3 library instead of mmap 2.'

