# md
# Autogenerated from man page /usr/share/man/man1/md.1
# using Darwin man parser
complete -c md -s D --description 'Specify debugging option(s): -tag -width indent… [See Man Page]'
complete -c md -s d --description 'Delete the . d file after it is processed.'
complete -c md -s f --description 'Force an update of the dependencies in the make… [See Man Page]'
complete -c md -s m --description 'Specify the makefile to be upgraded.'
complete -c md -s o --description 'Specify an output file (other than a makefile) … [See Man Page]'
complete -c md -s u --description 'Like m, but the file will be created if necessary.'
complete -c md -s v --description 'Set the verbose flag.'
complete -c md -s x --description 'Expunge old dependency information from the makefile.'

