# merge
# Autogenerated from man page /usr/share/man/man1/merge.1
# using Deroffing man parser
complete -c merge -s A --description 'Output conflicts using the  -A style of  diff3 … [See Man Page]'
complete -c merge -s L --description 'This option may be given up to three times, and… [See Man Page]'
complete -c merge -s p --description 'Send results to standard output instead of over… [See Man Page]'
complete -c merge -s E -s e --description 'These options specify conflict styles that gene… [See Man Page]'
complete -c merge -s q --description 'Quiet; do not warn about conflicts.'
complete -c merge -s V --description 'Print \'s version number.'

