# mk-ca-bundle
# Autogenerated from man page /opt/local/share/man/man1/mk-ca-bundle.1.gz
# using Darwin man parser
complete -c mk-ca-bundle -s b --description 'backup an existing version of ca-bundle. crt.'
complete -c mk-ca-bundle -s i --description 'print version info about used modules.'
complete -c mk-ca-bundle -s l --description 'print license info about certdata. txt.'
complete -c mk-ca-bundle -s n --description 'no download of certdata. txt (to use existing).'
complete -c mk-ca-bundle -s q --description 'be really quiet (no progress output at all).'
complete -c mk-ca-bundle -s t --description 'include plain text listing of certificates.'
complete -c mk-ca-bundle -s u --description 'unlink (remove) certdata. txt after processing.'
complete -c mk-ca-bundle -s v --description 'be verbose and print out processed CAs El EXIT … [See Man Page]'

