# mkafmmap
# Autogenerated from man page /usr/share/man/man1/mkafmmap.1.gz
# using Deroffing man parser
complete -c mkafmmap -s h -l help --description 'Show summary of options.'
complete -c mkafmmap -s v -l version --description 'Show version of program.'
complete -c mkafmmap -l output-file --description 'the map to stdout.'
complete -c mkafmmap -s p --description 'Print output to file NAME.'

