# neon-config
# Autogenerated from man page /opt/local/share/man/man1/neon-config.1.gz
# using Deroffing man parser
complete -c neon-config -l cflags --description 'Print the flags which should be passed to the C… [See Man Page]'
complete -c neon-config -l libs --description 'Print the flags which should be passed to the l… [See Man Page]'
complete -c neon-config -l la-file --description 'Print the location of the libtool library script, libneon.'
complete -c neon-config -l version --description 'Print the version of the library.'
complete -c neon-config -l prefix --description 'If dir is given; relocate output of --cflags an… [See Man Page]'
complete -c neon-config -l support --description 'The script exits with success if feature is sup… [See Man Page]'
complete -c neon-config -l help --description 'Print help message; includes list of known feat… [See Man Page]'

