# notifyutil
# Autogenerated from man page /usr/share/man/man1/notifyutil.1.gz
# using Darwin man parser
complete -c notifyutil -s p --description 'Post a notification for key.'
complete -c notifyutil -s w --description 'Register for key and wait for notifications.'
complete -c notifyutil -s '#' --description 'Register for key and wait for # (an integer) notifications.  E.'
complete -c notifyutil -s g --description 'Get state value for key.'
complete -c notifyutil -s s --description 'Set state value for key.'

