# ossp-uuid-config
# Autogenerated from man page /opt/local/share/man/man1/ossp-uuid-config.1.gz
# using Type1
complete -c ossp-uuid-config -l help --description 'Prints the short usage information.'
complete -c ossp-uuid-config -l version --description 'Prints the version number and date of the insta… [See Man Page]'
complete -c ossp-uuid-config -l all --description 'Forces the output of all flags, that is, includ… [See Man Page]'
complete -c ossp-uuid-config -l prefix --description 'Prints the installation prefix of architecture … [See Man Page]'
complete -c ossp-uuid-config -l exec-prefix --description 'Prints the installation prefix of architecture dependent files.'
complete -c ossp-uuid-config -l bindir --description 'Prints the installation directory of binaries.'
complete -c ossp-uuid-config -l libdir --description 'Prints the installation directory of libraries.'
complete -c ossp-uuid-config -l includedir --description 'Prints the installation directory of include headers.'
complete -c ossp-uuid-config -l mandir --description 'Prints the installation directory of manual pages.'
complete -c ossp-uuid-config -l datadir --description 'Prints the installation directory of shared data.'
complete -c ossp-uuid-config -l acdir --description 'Prints the installation directory of autoconf data.'
complete -c ossp-uuid-config -l cflags --description 'Prints the C compiler flags which are needed to… [See Man Page]'
complete -c ossp-uuid-config -l ldflags --description 'Prints the linker flags (\\f(CW\\*(C`-L\\*(C\') whi… [See Man Page]'

