# pcastlibraryredirector_start
# Autogenerated from man page /usr/share/man/man1/pcastlibraryredirector_start.1
# using Darwin man parser
complete -c pcastlibraryredirector_start -s a --description 'Description of -a flag.'
complete -c pcastlibraryredirector_start -s b --description 'Description of -b flag \\" Ends the list Pp .'

