# pcastlibrary
# Autogenerated from man page /usr/share/man/man1/pcastlibrary.1
# using Darwin man parser
complete -c pcastlibrary -l checkCredentials --description 'Verifies a username and password pair are valid… [See Man Page]'
complete -c pcastlibrary -l allCollections --description 'Returns a list of available collections.'
complete -c pcastlibrary -l collection --description 'Returns information about the collection with t… [See Man Page]'
complete -c pcastlibrary -l collectionsWithTitle --description 'Returns the UUIDs for all collections with the given title sp.'
complete -c pcastlibrary -l addCollection --description 'Adds a collection sp.'
complete -c pcastlibrary -l updateCollection --description 'Updates a collection sp.'
complete -c pcastlibrary -l deleteCollection --description 'Deletes a collection sp.'
complete -c pcastlibrary -l allDocuments --description 'Returns a list of documents sp.'
complete -c pcastlibrary -l document --description 'Returns the metadata for the document with the … [See Man Page]'
complete -c pcastlibrary -l deleteDocument --description 'Deletes the document with the specified UUID sp.'
complete -c pcastlibrary -l addDocument --description 'Adds a document sp.'
complete -c pcastlibrary -l updateDocument --description 'Adds a document Updates a document sp.'
complete -c pcastlibrary -l shareDocumentWithPodcastProducer --description 'Submits a document to a Podcast Producer system… [See Man Page]'

