# pcastlibrary_prerequisite_check
# Autogenerated from man page /usr/share/man/man1/pcastlibrary_prerequisite_check.1
# using Darwin man parser
complete -c pcastlibrary_prerequisite_check -s a --description 'Description of -a flag.'
complete -c pcastlibrary_prerequisite_check -s b --description 'Description of -b flag \\" Ends the list Pp .'

