# perfdiagnose
# Autogenerated from man page /usr/share/man/man1/perfdiagnose.1
# using Darwin man parser
complete -c perfdiagnose -s h --description 'Print full usage.'
complete -c perfdiagnose -s f --description 'Specify the directory where the results will be stored.'
complete -c perfdiagnose -s t --description 'Enable "Thorough Mode".  See below.'

