# podcastfeed
# Autogenerated from man page /usr/share/man/man1/podcastfeed.1
# using Darwin man parser
complete -c podcastfeed -s a --description 'Description of -a flag.'
complete -c podcastfeed -s b --description 'Description of -b flag \\" Ends the list Pp .'

