# port
# Autogenerated from man page /opt/local/share/man/man1/port.1.gz
# using Darwin man parser
complete -c port -s v --description 'verbose mode (generate verbose messages).'
complete -c port -s d --description 'debug mode (generate debugging messages, implies v ).'
complete -c port -s q --description 'quiet mode (suppress messages).'
complete -c port -s n --description 'don\'t upgrade dependencies (affects upgrade and install).'
complete -c port -s R --description 'also upgrade dependents (only affects upgrade) … [See Man Page]'
complete -c port -s u --description 'uninstall non-active ports when upgrading and uninstalling.'
complete -c port -s f --description 'force mode (ignore state file).'
complete -c port -s o --description 'honor state files even if the Portfile has been… [See Man Page]'
complete -c port -s s --description 'source-only mode (build and install from source… [See Man Page]'
complete -c port -s b --description 'binary-only mode (build and install from binary… [See Man Page]'
complete -c port -s c --description 'autoclean mode (execute clean after install).'
complete -c port -s k --description 'keep mode (don\'t autoclean after install).'
complete -c port -s D --description 'specify portdir.'
complete -c port -s F --description 'Read and process the file of commands specified… [See Man Page]'
complete -c port -s p --description 'Despite any errors encountered, proceed to proc… [See Man Page]'
complete -c port -s y --description 'Perform a dry run.'
complete -c port -s t --description 'enable trace mode debug facilities on platforms… [See Man Page]'

