# postconf
# Autogenerated from man page /usr/share/man/man1/postconf.1.gz
# using Deroffing man parser
complete -c postconf -s a --description 'List the available SASL server plug-in types.'
complete -c postconf -s A --description 'List the available SASL client plug-in types.'
complete -c postconf -s b --description 'Display the message text that appears at the be… [See Man Page]'
complete -c postconf -s c --description 'The main.'
complete -c postconf -s d --description 'Print default parameter settings instead of actual settings.'
complete -c postconf -s e --description 'Edit the main. cf configuration file.'
complete -c postconf -s h --description 'Show parameter values only, not the "name = " l… [See Man Page]'
complete -c postconf -s l --description 'List the names of all supported mailbox locking methods.'
complete -c postconf -s m --description 'List the names of all supported lookup table types.'
complete -c postconf -s n --description 'Print parameter settings that are not left at t… [See Man Page]'
complete -c postconf -s t --description 'Display the templates for delivery status notif… [See Man Page]'
complete -c postconf -s v --description 'Enable verbose logging for debugging purposes.'
complete -c postconf -s '#' --description 'Edit the main. cf configuration file.'

