# rcp
# Autogenerated from man page /usr/share/man/man1/rcp.1.gz
# using Darwin man parser
complete -c rcp -s 4 --description 'Use IPv4 addresses only.'
complete -c rcp -s 6 --description 'Use IPv6 addresses only.'

