# rcsclean
# Autogenerated from man page /usr/share/man/man1/rcsclean.1
# using Deroffing man parser
complete -c rcsclean -s k --description 'Use  subst style keyword substitution when retr… [See Man Page]'
complete -c rcsclean -s n --description 'Do not actually remove any files or unlock any revisions.'
complete -c rcsclean -s q --description 'Do not log the actions taken on standard output.'
complete -c rcsclean -s r --description 'This option has no effect other than specifying… [See Man Page]'
complete -c rcsclean -s T --description 'Preserve the modification time on the \\*r file … [See Man Page]'
complete -c rcsclean -s u --description 'Unlock the revision if it is locked and no difference is found.'
complete -c rcsclean -s V --description 'Print \\*r\'s version number.'
complete -c rcsclean -s x --description 'Use  suffixes to characterize \\*r files.'
complete -c rcsclean -s z --description 'Use zone as the time zone for keyword substitut… [See Man Page]'

