# rcsdiff
# Autogenerated from man page /usr/share/man/man1/rcsdiff.1
# using Deroffing man parser
complete -c rcsdiff -s q --description 'suppresses diagnostic output.'
complete -c rcsdiff -s r --description 'The option.'
complete -c rcsdiff -s k --description 'affects keyword substitution when extracting re… [See Man Page]'
complete -c rcsdiff -o kk -o 'r1.1' -o 'r1.2' --description 'ignores differences in keyword values when comp… [See Man Page]'
complete -c rcsdiff -o kkvl --description 'is assumed if (1) at most one revision option is given, (2) no.'
complete -c rcsdiff -o kkv --description 'is the default keyword substitution, and (4) th… [See Man Page]'
complete -c rcsdiff -s T --description '.'
complete -c rcsdiff -s V --description '.'
complete -c rcsdiff -s x --description 'and.'
complete -c rcsdiff -s z --description 'Otherwise, all options of diff (1) that apply t… [See Man Page]'

