# rcsmerge
# Autogenerated from man page /usr/share/man/man1/rcsmerge.1
# using Deroffing man parser
complete -c rcsmerge -s A --description 'Output conflicts using the  -A style of  diff3 … [See Man Page]'
complete -c rcsmerge -s k --description 'Use  subst style keyword substitution.'
complete -c rcsmerge -s p --description 'Send the result to standard output instead of o… [See Man Page]'
complete -c rcsmerge -s q --description 'Run quietly; do not print diagnostics.'
complete -c rcsmerge -s r --description 'Merge with respect to revision R rev .'
complete -c rcsmerge -s T --description 'This option has no effect; it is present for co… [See Man Page]'
complete -c rcsmerge -s V --description 'Print \\*r\'s version number.'
complete -c rcsmerge -s x --description 'Use  suffixes to characterize \\*r files.'
complete -c rcsmerge -s E -s e --description 'These options specify conflict styles that gene… [See Man Page]'
complete -c rcsmerge -o kk -o 'r1.1' -o 'r1.2' --description 'ignores differences in keyword values when merg… [See Man Page]'
complete -c rcsmerge -o kb --description 'expansion is used.'
complete -c rcsmerge -s z --description 'Use zone as the time zone for keyword substitution.'

