# readlink
# Autogenerated from man page /usr/share/man/man1/readlink.1.gz
# using Darwin man parser
complete -c readlink -s F --description 'As in ls 1, display a slash / immediately after… [See Man Page]'
complete -c readlink -s f --description 'Display information using the specified format.'
complete -c readlink -s L --description 'Use stat 2 instead of lstat 2.'
complete -c readlink -s l --description 'Display output in readlink ls Fl lT format.  ==========.'
complete -c readlink -s n --description 'Do not force a newline to appear at the end of … [See Man Page]'
complete -c readlink -s q --description 'Suppress failure messages if calls to stat 2 or lstat 2 fail.'
complete -c readlink -s r --description 'Display raw information.'
complete -c readlink -s s --description 'Display information in "shell output", suitable… [See Man Page]'
complete -c readlink -s t --description 'Display timestamps using the specified format.'
complete -c readlink -s x --description 'Display information in a more verbose way as kn… [See Man Page]'

