# reg
# Autogenerated from man page /usr/share/man/man1/reg.1
# using Darwin man parser
complete -c reg -s f --description '.'
complete -c reg -l format --description 'Specifies the format(s) to display values in.'
complete -c reg -s h --description '.'
complete -c reg -l help --description 'Prints brief usage information and exits.  Pp.'
complete -c reg -l verbose --description 'If used with no argument, enables verbose mode.'
complete -c reg -s v --description '.'
complete -c reg -l verify-writes --description 'If used with no argument, turns on write verification.'
complete -c reg -s V --description '.'
complete -c reg -l version --description 'Prints version information and exits.'

