# rlog
# Autogenerated from man page /usr/share/man/man1/rlog.1
# using Deroffing man parser
complete -c rlog -s R --description 'Print only the name of the \\*r file.'
complete -c rlog -s h --description 'Print only the \\*r pathname, working pathname, … [See Man Page]'
complete -c rlog -s t --description 'Print the same as  -h , plus the descriptive text.'
complete -c rlog -s N --description 'Do not print the symbolic names.'
complete -c rlog -s b --description 'Print information about the revisions on the de… [See Man Page]'
complete -c rlog -s d --description 'Print information about revisions with a checki… [See Man Page]'
complete -c rlog -s l --description 'Print information about locked revisions only.'
complete -c rlog -s r --description 'prints information about revisions given in the… [See Man Page]'
complete -c rlog -s s --description 'prints information about revisions whose state … [See Man Page]'
complete -c rlog -s w --description 'prints information about revisions checked in b… [See Man Page]'
complete -c rlog -s T --description 'This option has no effect; it is present for co… [See Man Page]'
complete -c rlog -s V --description 'Print \\*r\'s version number.'
complete -c rlog -s x --description 'Use  suffixes to characterize \\*r files.'
complete -c rlog -s z --description 'Without options, rlog prints complete information.'
complete -c rlog -s L --description 'Ignore RCSThis is convenient in combination with.'
complete -c rlog -o 'z	1990/01/12' --description '.'
complete -c rlog -o 'zLT	1990-01-11' --description '.'
complete -c rlog -o 'z+05:30	1990-01-12' --description 'EXAMPLES     rlog  -L  -R  RCS/*     rlog  -L  … [See Man Page]'

