# rsh
# Autogenerated from man page /usr/share/man/man1/rsh.1.gz
# using Darwin man parser
complete -c rsh -s 4 --description 'Use IPv4 addresses only.'
complete -c rsh -s 6 --description 'Use IPv6 addresses only.'
complete -c rsh -s t --description 'Allow a timeout to be specified (in seconds).'

