# rsync
# Autogenerated from man page /usr/share/man/man1/rsync.1.gz
# using Deroffing man parser
complete -c rsync -l force --description 'See also --keep-dirlinks for an analogous optio… [See Man Page]'
complete -c rsync -l extended-attributes --description 'Apple specific option to copy extended attribut… [See Man Page]'
complete -c rsync -l cache --description 'Apple specific option to enable filesystem cach… [See Man Page]'

