# stringdups
# Autogenerated from man page /usr/share/man/man1/stringdups.1.gz
# using Darwin man parser
complete -c stringdups -o minimumCount --description 'Only print information for object descriptions … [See Man Page]'
complete -c stringdups -o stringsOnly --description 'Only print information for objects that have st… [See Man Page]'
complete -c stringdups -o nostacks --description 'Do not print stack backtraces or call trees eve… [See Man Page]'
complete -c stringdups -o callTrees --description 'If stack bactraces are available, then by defau… [See Man Page]'
complete -c stringdups -o invertCallTrees --description 'Same as FL callTrees except that the call trees… [See Man Page]'

