# telnet
# Autogenerated from man page /usr/share/man/man1/telnet.1.gz
# using Darwin man parser
complete -c telnet -s 4 --description 'Forces telnet to use IPv4 addresses only.'
complete -c telnet -s 6 --description 'Forces telnet to use IPv6 addresses only.'
complete -c telnet -s N --description 'Prevents IP address to name lookup when destina… [See Man Page]'
complete -c telnet -s s --description 'Set the source IP address for the telnet connec… [See Man Page]'
complete -c telnet -s u --description 'Forces telnet to use AF_UNIX addresses only (e. g.'
complete -c telnet -s y --description 'Suppresses encryption of the data stream.'

