# twdiff
# Autogenerated from man page /usr/local/share/man/man1/twdiff.1
# using Type1
complete -c twdiff -l case-sensitive --description 'Equivalent to the \\*(L"Case Sensitive\\*(R" opti… [See Man Page]'
complete -c twdiff -l flatten-folders --description 'Equivalent to the \\*(L"Flatten Hierarchies\\*(R"… [See Man Page]'
complete -c twdiff -l help --description 'Display a basic help line with a summary of the… [See Man Page]'
complete -c twdiff -l ignore-curly-quotes --description 'Equivalent to the \\*(L"Ignore Curly Quotes\\*(R"… [See Man Page]'
complete -c twdiff -l ignore-extra-spaces --description 'Equivalent to the \\*(L"Ignore Spaces: Runs\\*(R"… [See Man Page]'
complete -c twdiff -l ignore-leading-spaces --description 'Equivalent to the \\*(L"Ignore Spaces: Leading\\*… [See Man Page]'
complete -c twdiff -l ignore-trailing-spaces --description 'Equivalent to the \\*(L"Ignore Spaces: Trailing\\… [See Man Page]'
complete -c twdiff -l ignore-spaces --description 'Equivalent to using all three of the preceding --ignore.'
complete -c twdiff -l resume --description 'Used in combination with --wait, this switch wi… [See Man Page]'
complete -c twdiff -l reverse --description 'Reverses the order of the arguments passed to BBEdit.'
complete -c twdiff -l short-version --description 'Display the short-form version number of the tw… [See Man Page]'
complete -c twdiff -l show-identical-files --description 'Equivalent to the \\*(L"List Identical Files\\*(R… [See Man Page]'
complete -c twdiff -l skip-shielded-folders --description 'Equivalent to the \\*(L"Skip (.'
complete -c twdiff -l text-files-only --description 'Equivalent to the \\*(L"Only List Text Files\\*(R… [See Man Page]'
complete -c twdiff -l version --description 'Display the current version number of the twdif… [See Man Page]'

