# twm
# Autogenerated from man page /usr/X11/man/man1/twm.1.gz
# using Deroffing man parser
complete -c twm -o display --description 'This option specifies the X server to use.'
complete -c twm -s s --description 'This option indicates that only the default scr… [See Man Page]'
complete -c twm -s f --description 'This option specifies the name of the startup file to use.'
complete -c twm -s v --description 'This option indicates that twm should print err… [See Man Page]'

