# unlink
# Autogenerated from man page /usr/share/man/man1/unlink.1.gz
# using Darwin man parser
complete -c unlink -s d --description 'Attempt to remove directories as well as other types of files.'
complete -c unlink -s f --description 'Attempt to remove the files without prompting f… [See Man Page]'
complete -c unlink -s i --description 'Request confirmation before attempting to remov… [See Man Page]'
complete -c unlink -s P --description 'Overwrite regular files before deleting them.'
complete -c unlink -s R --description 'Attempt to remove the file hierarchy rooted in … [See Man Page]'
complete -c unlink -s r --description 'Equivalent to R.'
complete -c unlink -s v --description 'Be verbose when deleting files, showing them as… [See Man Page]'
complete -c unlink -s W --description 'Attempt to undelete the named files.'

