# uxterm
# Autogenerated from man page /usr/X11/man/man1/uxterm.1.gz
# using Deroffing man parser
complete -c uxterm -o class --description 'and.'
complete -c uxterm -o u8 --description 'options should not be specified because they ar… [See Man Page]'

