# vgrind
# Autogenerated from man page /usr/share/man/man1/vgrind.1
# using Darwin man parser
complete -c vgrind -s d --description 'specifies an alternative language definitions f… [See Man Page]'
complete -c vgrind -s f --description 'forces filter mode.'
complete -c vgrind -s h --description 'specifies a particular header to put on every o… [See Man Page]'
complete -c vgrind -s l --description 'specifies the language to use.'
complete -c vgrind -s n --description 'forces no keyword bolding.'
complete -c vgrind -s s --description 'specifies a point size to use on output (exactl… [See Man Page]'
complete -c vgrind -s t --description 'similar to the same option in troff causing for… [See Man Page]'
complete -c vgrind -s W --description 'forces output to the (wide) Versatec printer ra… [See Man Page]'
complete -c vgrind -s x --description 'outputs the index file in a ``pretty\'\' format.'

