# vmmap
# Autogenerated from man page /usr/share/man/man1/vmmap.1.gz
# using Darwin man parser
complete -c vmmap -s d --description 'Take two snapshots of the vm regions of the pro… [See Man Page]'
complete -c vmmap -s w --description 'Print wide output.'
complete -c vmmap -o resident --description 'Show both the virtual and resident sizes for ea… [See Man Page]'
complete -c vmmap -o pages --description 'Print region sizes in page counts rather than kilobytes.'
complete -c vmmap -o interleaved --description 'Print all regions in ascending order of startin… [See Man Page]'
complete -c vmmap -o submap --description 'Print information about VM submaps.'
complete -c vmmap -o allSplitLibs --description 'Print information about all shared system split… [See Man Page]'
complete -c vmmap -o noCoalesce --description 'Do not coalesce adjacent identical regions.'
complete -c vmmap -s v --description 'Equivalent to w resident dirty purge submap all… [See Man Page]'

