# xcode-select
# Autogenerated from man page /usr/share/man/man1/xcode-select.1
# using Darwin man parser
complete -c xcode-select -o help --description 'Prints the usage message.'
complete -c xcode-select -o switch --description 'Sets the path to the current Xcode, e. g.  "/Xcode4. 2".'
complete -c xcode-select -o print-path --description 'Prints the path of the current Xcode folder.'
complete -c xcode-select -o version --description 'Prints xcode-select version information.'

