# xcodebuild
# Autogenerated from man page /usr/share/man/man1/xcodebuild.1
# using Darwin man parser
complete -c xcodebuild -o project --description 'Build the project specified by projectname.'
complete -c xcodebuild -o target --description 'Build the target specified by targetname.'
complete -c xcodebuild -o alltargets --description 'Build all the targets in the specified project.'
complete -c xcodebuild -o workspace --description 'Build the workspace specified by workspacename.'
complete -c xcodebuild -o scheme --description 'Build the scheme specified by schemename.'
complete -c xcodebuild -o configuration --description 'Use the build configuration specified by config… [See Man Page]'
complete -c xcodebuild -o arch --description 'Use the architecture specified by architecture … [See Man Page]'
complete -c xcodebuild -o sdk --description 'Build an Xcode project or workspace against the… [See Man Page]'
complete -c xcodebuild -o showsdks --description 'Lists all available SDKs that Xcode knows about… [See Man Page]'
complete -c xcodebuild -o list --description 'Lists the targets and configurations in a proje… [See Man Page]'
complete -c xcodebuild -o xcconfig --description 'Load the build settings defined in filename whe… [See Man Page]'
complete -c xcodebuild -o version --description 'Display version information for this install of Xcode.'
complete -c xcodebuild -o usage --description 'Displays usage information for xcodebuild.'

