# xmh
# Autogenerated from man page /usr/X11/man/man1/xmh.1.gz
# using Deroffing man parser
complete -c xmh -o path --description 'This option specifies an alternate collection o… [See Man Page]'
complete -c xmh -o initial --description 'This option specifies an alternate folder which… [See Man Page]'
complete -c xmh -o flag --description 'This option will cause xmh to change the appear… [See Man Page]'

