# xmllint
# Autogenerated from man page /usr/share/man/man1/xmllint.1.gz
# using Deroffing man parser
complete -c xmllint -l xmlout --description 'Used in conjunction with.'
complete -c xmllint -l 'html.' --description 'HTML is parsed the document is saved with the HTML serializer.'

