# xtrap
# Autogenerated from man page /usr/X11/man/man1/xtrap.1.gz
# using Deroffing man parser
complete -c xtrap -o 'd[isplay]' --description 'Specifies the server to record from or playback to; see .'
complete -c xtrap -s e --description 'Record only (and all) events.'
complete -c xtrap -s f --description 'The pathname of the script to be recorded / played back. PP.'
complete -c xtrap -s v --description 'Verbose mode.'

